//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrMngSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int taskID { get; set; }
        public int projectID { get; set; }
        public Nullable<decimal> progress { get; set; }
        public System.DateTime deadline { get; set; }
        public string description { get; set; }
        public int status { get; set; }
        public Nullable<int> assignee { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual User User { get; set; }
    }
}
