//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrMngSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        [Browsable(false)]
        public int taskID { get; set; }
        [Display(Name = "Project ID")]
        public int projectID { get; set; }
        [Display(Name = "Progress %")]
        public Nullable<decimal> progress { get; set; }
        [Display(Name = "Deadline")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime deadline { get; set; }
        [Display(Name = "Description")]
        public string description { get; set; }
        [Display(Name = "Status")]
        public int status { get; set; }
        [Display(Name = "Assignee")]
        public Nullable<int> assignee { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual User User { get; set; }
    }
}
